common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
# urlpatterns = []
# urlpatterns = [
#     path('login/', auth_views.LoginView.as_view(), name='login'),
# ]

# [21-12-13] django.contib.auth앱의 LoginView 클래스 활용, views.py 파일 수정 필요 없음
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

# [21-12-13] 로그인 : settings.py 의 'INSTALLED_APPS'에 'common.apps.CommonConfig', 추가 후 사용
# / 페이지에 해당하는 url패턴
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('pybo/', views.index),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from .views import base_views, question_views, answer_views, comment_views, vote_views

# [21-12-06] pybo/urls.py 파일에 네임 스페이스 추가
app_name = 'pybo'

urlpatterns = [
    path('', base_views.index, name='index'),
    # [21-12-03] url 경로 오류시 views.py와 url 연결 추가하기
    path('<int:question_id>/', base_views.detail, name='detail'),
    # [21-12-06] 사용자가 상세 화면에서〈질문답변〉버튼을 눌렀을 때 작동할
    # form 엘리먼트의 /pybo/answer/create/2/에 대한 URL 매핑을 추가한 것
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    # [21-12-14] 질문 수정 버튼 url 매핑
    path('question/modify/<int:question_id>/', views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete,
         name='question_delete'),
    # [21-12-14] 답변 수정 버튼 url 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify,
         name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete,
         name='answer_delete'),
    # [21-12-15] 질문 댓글
    path('comment/create/question/<int:question_id>/', views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question,
         name='comment_delete_question'),
    # [21-12-15] 답변 댓글
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer,
         name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer,
         name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer,
         name='comment_delete_answer'),
    # [21-12-15] vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question,
         name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer,
         name='vote_answer'),
]

pybo/views/base_views.py
# from django.http import HttpResponse
from django.db.models import Q, Count
# [21-12-13] 페이징 기능 구현

from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question
import logging
logger = logging.getLogger(__name__)


# [21-12-15] views.py 파일 분리
def index(request):
    logger.info("INFO 레벨로 출력")
    # [21-12-03] pybo 목록 출력: 작성 날짜의 역순
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    # return HttpResponse("안녕하세요 pybo에 오신것을 환영 합니다.12-02 시작")
    # [21-12-13] 페이징 기능 입력 인자, pybo 목록 출력
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recentd')

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-creat_date')
    else: # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()


    #페이징 처리 - 페이지당 10개씩 보여주기
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    # [21-12-03] pypo 내용 출력 : urls.py에 있는  path('<int:question_id>/', views.detail),과 연결
    # question = Question.objects.get(id=question_id) ,없는 페이지를 반환 할때 에러 처리가 필요하다.
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=l, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Ocean Freight Quotation System</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<!-- [21-12-13] 네비게이션바 로고,로그인 링크 추가하기-->
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End-->
<!-- [21-12-13] jQuery JS-->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- [21-12-13] Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}

<!-- JavaScript End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        <!-- 필드 오류를 출력한다. -->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
            {{error}}
            </div>
        {% endfor %}
    {% endfor %}
    <!-- 넌필드 오류를 출력한다. -->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
        <strong>{{error}}}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- [21-12-13] 내비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
   <a class ="navbar-brand" href="{% url 'pybo:index' %}" >Ocean Freight Quotation System Q&A</a>
   <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
           data-target="#navbarNav" aria-controls="navbarNav"
           aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
       <ul class="navbar-nav">
           <li class="nav-item">
            {% if user.is_authenticated %}
               <a class="nav-link" href="{% url 'common:logout' %}">
               {{ user.username }} Logout</a>
               {% else %}
               <a class="nav-link" href="{% url 'common:login' %}">Login</a>
               {% endif %}
           </li>
       </ul>
   </div>
</nav>